print("1")
print("÷")
print("0")
print()
print("infinity")
v = (input())

print("PinoCalculator/Division")
No1 = (float(input()))
print("÷")
No2 = (float(input()))
print()
print( No1 / No2 )
print( No1 // No2 )
print()
print("PinoCalculator/Division")
No1 = (float(input()))
print("÷")
No2 = (float(input()))
print()
print( No1 / No2 )
print( No1 // No2 )
print()
print("PinoCalculator/Division")
No1 = (float(input()))
print("÷")
No2 = (float(input()))
print()
print( No1 / No2 )
print( No1 // No2 )
print()