
print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print( No1 //No2 )
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")

print('Welcome to Python  Division Calculator')
No1 = (float(input()))
print("/")
No2 = (float(input()))
Answer = (No1 / No2)
print(Answer)
print("")
print("")
